math:
    userName: unnamed user 
    num_tasks: 10
    wrongSolution: 0
    factoryDecision: 0

spring:
  datasource:
    url: jdbc:mysql://localhost/math4juerina
    username: root
#    password: fhfgh


